apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  selector:
    matchLabels:
      app: petclinic-deployment
  replicas: 1 
  template:
    metadata:
      labels:
        app: petclinic-deployment
    spec:
      containers:
      - name: petclinic-deployment
        image:  908207384553.dkr.ecr.us-east-2.amazonaws.com/pet:1
        ports:
        - containerPort: 8080


kind: Service
apiVersion: v1
metadata:
  name: petclinic-service
  namespace: animals
spec:
  selector:
    app: petclinic-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080









apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ing
  namespace: animals
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 

    http:
      paths:
      - path:
        backend:
          serviceName: petclinic-service
          servicePort: 80
